# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e60cb8421d036eec4e8be58e6b0819f309b634064b6ba0f7f7ebbb54fea8c9b5de2e860e5c07cef09373eae99957b6b6bdd1d170ed9982e7bae9327ff8e7821

test:
  secret_key_base: a1e4476739da4ff86b18d4c9ce7aead7d64ea633c1b24dc204297284c4974acb3aa86866dfdc13b29e1d3564fcf7dbab6cca780fd6404e7478c0decca84f69c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
