# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b44ba8cf8d8811722a172301fcbad90042c7428c6c2b954b2dcc67db19f47a60eb19598ccd67974b842e5c5d7e3425f1aae65f2eb771d06b07f8dea7f1fe4079

test:
  secret_key_base: dc99ea5c033632805244c30a9a4f99adc7a0da7ac95c6862825d21e050c564382658c5cd079709b39417d155427b7c1c56cec2445cde2ac5f03ccd4b08064fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
