# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b82e9cc792e6f5c11d4eb766dc6b3f51a52e80c3ab090405b7af7ad4989de0f2440e695cdaf308d0c55b568a641b2e3ad2efb50fa5c43ba3523399ae2e4bac1

test:
  secret_key_base: f3f1aab56183c29d2f95147c2f1ec93b9cbb0eaa38b5f983c6ad36d401b604bb0e64b27279812b3b74b8b8264bfd8179531b2986d0db75d0096c17c6c1c4598e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
