# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 437967c0fedaf1bf6b9ccbec3c58c7c906f6a06dd0ced35a724bb8d64e2fcee57a35adca683ee507c279ca90c55c1e7c9b66e0e630d234e1aa7e0fd1da6cd4eb

test:
  secret_key_base: 5185be412d2923c07f80344b6babf7e7326c293149b38e47f49c3808bef515b92791467b283dc8f9d44b70f8c510013277965474b922bd5b1d231f41f2b3629b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
