# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3893c4447765d75077f804364f93e8280cf3cda9d3a8b983c178f80a4cd7349eacf755c7c2245e2ae07273201e48524995303788377e587c26893e8dc0b4404e

test:
  secret_key_base: 5fa525d287f8710d42a04a4384634d9eabcca4576c7295afb0bc621c85ab87e99cf4c32b358c620d12699d7006993a6ea376bc17e3222a7d24d46830a1087130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
